version: '3.1'
services:
  php-applications:
    container_name: cicd_docker_github
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/